const assert = require('node:assert/strict');
const J = require('../journal-state.js');
const fs = require('node:fs'), vm = require('node:vm'), path = require('node:path');
const lifeSource = fs.readFileSync(path.join(__dirname,'../life.js'),'utf8');
const sanitizeSource = lifeSource.slice(lifeSource.indexOf('  function initial()'),lifeSource.indexOf('  function state()'));
const sanitize = vm.runInThisContext('(function(window){'+sanitizeSource+';return sanitize;})')({});
const life={gems:7,planner:{tasks:[{id:'a',done:true}]},days:{'2026-10-01':{words:50,focusMinutes:25,food:{note:'旧饮食',photoId:'old-photo'}},'2026-10-02':{entries:[{id:'text',text:'文字',createdAt:1},{id:'photo',photoId:'new-photo',createdAt:2},{id:'both',text:'照片配字',photoId:'new-photo',createdAt:3}]},'2026-10-03':{words:20}}};
assert.deepEqual(J.summary(life),{count:4,days:2,photos:3});
assert.deepEqual(J.photoIds(life),['new-photo','old-photo']);
assert.deepEqual(J.counts(life),{'2026-10-01':1,'2026-10-02':3});
assert.equal(J.entries(life,'2026-10-02')[0].id,'both');
J.remapPhotos(life,{'new-photo':'restored','old-photo':'restored-old'});
assert.deepEqual(J.photoIds(life),['restored','restored-old']);
assert.equal(life.gems,7);assert.equal(life.days['2026-10-01'].words,50);assert.equal(life.days['2026-10-01'].focusMinutes,25);assert.equal(life.planner.tasks[0].done,true);
assert.equal(J.shift('2026-12-31',1),'2027-01-01');
const cleaned=sanitize(life);
assert.deepEqual(J.summary(cleaned),{count:4,days:2,photos:3});
assert.deepEqual(J.photoIds(cleaned),['restored','restored-old']);
assert.equal(cleaned.days['2026-10-02'].entries[0].createdAt,1);
assert.deepEqual(J.summary(sanitize(JSON.parse(JSON.stringify(cleaned)))),J.summary(cleaned));
const rewardedDay=sanitize({version:1,gems:2,days:{'2026-10-04':{entryRewarded:true,entries:[{id:'e',text:'今天',createdAt:1}]},'2026-10-05':{entryRewarded:'yes'}}});
assert.equal(rewardedDay.days['2026-10-04'].entryRewarded,true);assert.equal(rewardedDay.days['2026-10-05'].entryRewarded,undefined);assert.equal(rewardedDay.gems,2);
console.log('Journal counts, legacy records, photo remapping and existing planner data passed.');
